// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBeFM_lcDkzoxIl22HEfysDdQ1Mousq8s',
    appId: '1:66873610716:web:db192540c44c62e3007f19',
    messagingSenderId: '66873610716',
    projectId: 'daymatch-fe77a',
    authDomain: 'daymatch-fe77a.firebaseapp.com',
    storageBucket: 'daymatch-fe77a.firebasestorage.app',
    measurementId: 'G-LBEBMHZN2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzR6zUoY90jnbtoZtdswc5gfSpJYjlHtw',
    appId: '1:66873610716:android:e3d7adfe6b789882007f19',
    messagingSenderId: '66873610716',
    projectId: 'daymatch-fe77a',
    storageBucket: 'daymatch-fe77a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV757ebBkV2g5Kt0J0PAfMprjPxV04u_A',
    appId: '1:66873610716:ios:b22438e2a169ec84007f19',
    messagingSenderId: '66873610716',
    projectId: 'daymatch-fe77a',
    storageBucket: 'daymatch-fe77a.firebasestorage.app',
    iosBundleId: 'com.daymatch.daymatch',
  );
}
